# ### Normal config with one wallpaper ###
# preload = ~/wallpapers/evening-sky.png
# wallpaper = , ~/wallpapers/evening-sky.png

##### STAR WARS 3 wallpaper config ###
# preload = ~/wallpapers/star-wars/star-wars-blue.jpg
# preload = ~/wallpapers/star-wars/star-wars-red.jpeg
# preload = ~/wallpapers/star-wars/star-wars-combined-orange-green.jpg
#
# wallpaper = HDMI-A-1, ~/wallpapers/star-wars/star-wars-blue.jpg
# wallpaper = DP-1, ~/wallpapers/star-wars/star-wars-combined-orange-green.jpg
# wallpaper = DP-2, ~/wallpapers/star-wars/star-wars-red.jpeg


### COOL Astronaughts ###
# preload = ~/wallpapers/wide/cool.jpg
#
# wallpaper = HDMI-A-1, ~/wallpapers/wide/cool.jpg
# wallpaper = DP-1, ~/wallpapers/wide/cool.jpg
# wallpaper = DP-2, ~/wallpapers/wide/cool.jpg

##### Yellow theme ####
# $vertical = ~/wallpapers/vertical/summer-palms.jpg
# $horizontal = ~/wallpapers/wide/yellow-flowers-5120x2880.png

##### flowery machiatto theme ####
$vertical = ~/wallpapers/vertical/prickly.png
$horizontal = ~/wallpapers/wide/flowers-13.jpg

preload = $vertical
preload = $horizontal

wallpaper = HDMI-A-1, $vertical
wallpaper = DP-1, $horizontal
wallpaper = DP-2, $vertical
